### ISSUE TITLE
无法跳转和提示

### ISSUE THREAD

**Issue by ALongLi** [IWANABETHATGUY/vscode-path-alias#16]
vscode版本
![1569721191(1)](https://user-images.githubusercontent.com/20749911/65824531-32b55c00-e29d-11e9-85fa-a90b8946239e.png)

操作gif
![path](https://user-images.githubusercontent.com/20749911/65824519-0dc0e900-e29d-11e9-8da8-ac54e55e8066.gif)

**Comment by IWANABETHATGUY** [comment]
我在win10上测试的没问题。
