### ISSUE TITLE
跳转异常

### ISSUE THREAD

**Issue by ALongLi** [IWANABETHATGUY/vscode-path-alias#17]
比如vscode工作区两个项目
vue-demo1
vue-demo2

第一个项目
├─.browserslistrc 
├─.eslintrc.js 
├─.gitignore 
├─babel.config.js 
├─mock 
├─package-lock.json 
├─package.json 
├─postcss.config.js 
├─public 
├─src 
│ ├─App.vue 
│ ├─assets 
│ ├─components 
│ ├─fetch 
│ │ ├─excelDownload.js 
│ │ ├─index.js 
│ │ └─instance.js 
│ ├─filters 
│ │ └─index.js 
│ ├─lib 
│ │ ├─eoa.js 
│ │ └─initEcharts.js 
│ ├─main.js 
│ ├─router.js 
│ ├─skeleton 
│ ├─store.js 
│ ├─utils 
│ │ └─dom.js 
│ └─views 
│   ├─demo.vue 
│   └─Home.vue ------------ // 这里引入了fetch/index.js
└─vue.config.js 
第二个项目
├─.browserslistrc 
├─.eslintrc.js 
├─.gitignore 
├─babel.config.js 
├─mock 
├─package-lock.json 
├─package.json 
├─postcss.config.js 
├─public 
├─src 
│ ├─App.vue 
│ ├─assets 
│ ├─components 
│ ├─fetch 
│ │ ├─excelDownload.js 
│ │ ├─index.js 
│ │ └─instance.js 
│ ├─filters 
│ │ └─index.js 
│ ├─lib 
│ │ ├─eoa.js 
│ │ └─initEcharts.js 
│ ├─main.js 
│ ├─router.js 
│ ├─skeleton 
│ ├─store.js 
│ ├─utils 
│ │ └─dom.js 
│ └─views 
│   ├─demo.vue 
│   └─Home.vue ------------ // 这里引入了fetch/index.js
└─vue.config.js 

在vue-demo2项目的Home.vue点击引入的@fetch/index.js ,跳转到了第一个项目中
第一个项目是正常的，就是后面的项目文件路径如果在第一个项目中有对应的文件，会跳转到第一个项目里

**Comment by IWANABETHATGUY** [comment]
你的意思是在一个工作区里打开两个工作目录吗？

**Comment by ALongLi** [comment]
是的 @IWANABETHATGUY

**Comment by ALongLi** [comment]
路径提示也是同样的问题，应该是根目录计算错了，一直是工作区第一个项目目录 @IWANABETHATGUY

**Comment by IWANABETHATGUY** [comment]
> 路径提示也是同样的问题，应该是根目录计算错了，一直是工作区第一个项目目录 @IWANABETHATGUY

也不算是bug，因为这个功能目前只做了单个工作目录的，等以后有时间再加吧，你可以尝试提个pr

**Comment by limodou** [comment]
我也遇到这个问题。简单的做法有两点：
1. 把@等的替换放在 provideDefinition 定义中，这样可以根据document来动态判断需要查找的根目录
2. 根目录的判断是可以利用是否有package.json来判断。

比如：

```
  getWorkDir (document: TextDocument): string {
    let filepath = document.uri.fsPath;
    let curDir = '';
    // 查找父目录
    while (1) {
      let dir = path.dirname(filepath);
      if (fs.existsSync(path.join(dir, 'package.json'))) {
        curDir = dir;
        break;
      }
      filepath = dir;
    }
    return curDir
  }
```

供参考。本地安装npm install 总是取vscode.d.ts报错，没法调试。

**Comment by IWANABETHATGUY** [comment]
已经提供了多目录的路径别名功能，今天测试下，下个版本发

**Comment by IWANABETHATGUY** [comment]
已经发布了
