### ISSUE TITLE
老哥，能从 cwd 获取配置文件吗？

### ISSUE THREAD

**Issue by hifizz** [IWANABETHATGUY/vscode-path-alias#18]

**Comment by IWANABETHATGUY** [comment]
你说的是从cwd目录下的配置文件获取路径别名的定义吗？

**Comment by hifizz** [comment]
> 你说的是从cwd目录下的配置文件获取路径别名的定义吗？

是的，因为对于团队使用，设置到setting里面不太合适，不适用。所以如果是可以从项目根目录写配置文件可以解决，就像 tsconfig.json 一样

**Comment by IWANABETHATGUY** [comment]
> > 你说的是从cwd目录下的配置文件获取路径别名的定义吗？
> 
> 是的，因为对于团队使用，设置到setting里面不太合适，不适用。所以如果是可以从项目根目录写配置文件可以解决，就像 tsconfig.json 一样

下一版做吧，可以考虑添加一个像prettierrc 那样的配置文件，也考虑从vue.config.json, webpack.config.json中获取alias

**Comment by IWANABETHATGUY** [comment]
已经完成，请下载最新版本的插件体验
