### ISSUE TITLE
请教从相对路径到路径别名的重构的使用方式

### ISSUE THREAD

**Issue by Jen0** [IWANABETHATGUY/vscode-path-alias#30]
这个插件是真的好用，请教从相对路径到路径别名的重构的使用方式，是用快捷键吗？

**Comment by IWANABETHATGUY** [comment]
将光标移动到相对路径上会出来一个小灯泡，点击小灯泡选择路径别名即可

**Comment by Jen0** [comment]
> 将光标移动到相对路径上会出来一个小灯泡，点击小灯泡选择路径别名即可

![image](https://user-images.githubusercontent.com/29544549/68374215-69757080-017f-11ea-98d5-3fffb7009dd4.png)
可是我的win10（vscode 版本1.39.2）没有看到过小灯泡耶。。？

**Comment by IWANABETHATGUY** [comment]
![image](https://user-images.githubusercontent.com/17974631/68374509-fc160f80-017f-11ea-8e38-1833b39d701c.png)

**Comment by Jen0** [comment]
![image](https://user-images.githubusercontent.com/29544549/68374970-db01ee80-0180-11ea-9b06-17030eabb8c9.png)
换了个主题，也没有看到。。。尴尬了

**Comment by IWANABETHATGUY** [comment]
是光标移动到路径别名，不是鼠标。。。

**Comment by Jen0** [comment]
![image](https://user-images.githubusercontent.com/29544549/68375421-c8d48000-0181-11ea-872a-e1e473169f38.png)
。。。小灯泡怎么都不出来

**Comment by IWANABETHATGUY** [comment]
我专门去win10 下试了试，正常的。
检查下你的路径别名映射表有没有正确写好，你的相对路径必须在路径映射表的绝对路径下才能正常重构。

**Comment by Jen0** [comment]
![image](https://user-images.githubusercontent.com/29544549/68376272-4ea4fb00-0183-11ea-9d69-c9e1813fb388.png)
只是配置了这个。

**Comment by IWANABETHATGUY** [comment]
你把你的项目目录发一下

**Comment by Jen0** [comment]
![image](https://user-images.githubusercontent.com/29544549/68376579-c541f880-0183-11ea-92f7-88e16527d76b.png)

**Comment by IWANABETHATGUY** [comment]
提示正常吗？

**Comment by Jen0** [comment]
![path](https://user-images.githubusercontent.com/29544549/68377247-fe2e9d00-0184-11ea-828d-86c6ea346dae.gif)
提示正常。

**Comment by IWANABETHATGUY** [comment]
这我真的没办法，这功能挺鸡肋，还有就是我没有办法复现你的问题，等我遇到，再尝试修复吧。

**Comment by Jen0** [comment]
嗯嗯，虽然暂时没有解决，还是得感谢下你。

**Comment by Jen0** [comment]
今天用mac试了一下，完美运行！👍
