### ISSUE TITLE
添加输入一级后自动显示下一级的目录和文件

### ISSUE THREAD

**Issue by xluos** [IWANABETHATGUY/vscode-path-alias#32]
现在的方式是选择补全的一级之后要手动打上/才会有下一级的补全，能否改为如果选择的是目录，就接着显示下一级的目录或文件，这样子连续选择效率更好些

**Comment by xluos** [comment]
或者是像原生的补全一样显示两个选项
![image](https://user-images.githubusercontent.com/23625189/69937105-c5c87780-1514-11ea-8533-83cbe6fd275a.png)

**Comment by IWANABETHATGUY** [comment]
提供两个选项以后，你输入/ 比按方向下键应该还快吧

**Comment by xluos** [comment]
这个个人习惯问题吧  我感觉选择了之后直接可以继续选择整体流程更连贯一些。还是希望能支持一下这种方式，加个可以自动显示下一级的配置之类的

**Comment by IWANABETHATGUY** [comment]
已经解决，将在下一个版本发布
