### ISSUE TITLE
引入的时候省略 '/index' 无法跳转

### ISSUE THREAD

**Issue by HenryTSZ** [IWANABETHATGUY/vscode-path-alias#34]
比如有这样一个路径:

```
├─src
│ ├─index.js
│ ├─api.js
```

已配置 `src` 路径别名, `src/api` 可以正常跳转, `src` 无法跳转, `src/index` 可以正常跳转.

还有一个问题: 在 `.vue` 文件中引入 `vue` 文件不加后缀可以跳转, 在 `.js` 中必须加后缀才能跳转

**Comment by IWANABETHATGUY** [comment]
为了没有歧义， 同类型文件优先级最高，要不然如果你目录下同时有一个 `test.vue`, `test.js`, 这时候 你省略 后缀应该跳转到哪呢？这个好像没有问题

**Comment by HenryTSZ** [comment]
> 为了没有歧义， 同类型文件优先级最高，要不然如果你目录下同时有一个 `test.vue`, `test.js`, 这时候 你省略 后缀应该跳转到哪呢？这个好像没有问题

已配置 `src` 路径别名, `src/api` 可以正常跳转, `src` 无法跳转, `src/index` 可以正常跳转.

那这个问题可以解决吗?

**Comment by IWANABETHATGUY** [comment]
> > 为了没有歧义， 同类型文件优先级最高，要不然如果你目录下同时有一个 `test.vue`, `test.js`, 这时候 你省略 后缀应该跳转到哪呢？这个好像没有问题
> 
> 已配置 `src` 路径别名, `src/api` 可以正常跳转, `src` 无法跳转, `src/index` 可以正常跳转.
> 
> 那这个问题可以解决吗?

你的意思是从 `src` 跳转到 `src/index.js` 吗？

**Comment by HenryTSZ** [comment]
> > > 为了没有歧义， 同类型文件优先级最高，要不然如果你目录下同时有一个 `test.vue`, `test.js`, 这时候 你省略 后缀应该跳转到哪呢？这个好像没有问题
> > 
> > 
> > 已配置 `src` 路径别名, `src/api` 可以正常跳转, `src` 无法跳转, `src/index` 可以正常跳转.
> > 那这个问题可以解决吗?
> 
> 你的意思是从 `src` 跳转到 `src/index.js` 吗？

对的

**Comment by IWANABETHATGUY** [comment]
升级到最新的版本试试， 我这边没有问题

**Comment by IWANABETHATGUY** [comment]
如果有问题，欢迎再 开一个 issue
