### ISSUE TITLE
.pathaliasrc 无法跳转

### ISSUE THREAD

**Issue by HenryTSZ** [IWANABETHATGUY/vscode-path-alias#35]
在系统的 `setting.json` 中配置`pathAlias.aliasMap`, 里面有一个路径别名的路径是错误的, `.pathaliasrc` 中是正确的, 但无法跳转, 只有注释掉 `setting.json` 中的配置才能跳转. `.pathaliasrc` 的优先级应该高于 `setting.json` 吧

**Comment by IWANABETHATGUY** [comment]
.pathaliasrc 优先级是比 setting.json 里的配置高的，需要把你的pathaliasrc 和 setting.json 发给我一下。

**Comment by HenryTSZ** [comment]
.pathaliasrc:

```json
{
  "@": "${cwd}/src",
  "api": "${cwd}/src/api",
  "assets": "${cwd}/src/assets",
  "components": "${cwd}/src/components",
  "plugins": "${cwd}/src/plugins",
  "store": "${cwd}/src/store",
  "utils": "${cwd}/src/utils",
  "views": "${cwd}/src/views",
  "rootAssets": "${cwd}/../Plugins/src/assets",
  "rootPlugins": "${cwd}/../Plugins/src/plugins",
  "rootUtils": "${cwd}/../Plugins/src/utils"
}
```

setting.json: 

```json
// 配置路径别名
"pathAlias.aliasMap": {
  "@": "${cwd}/src",
  "api": "${cwd}/src/api",
  "assets": "${cwd}/src/assets",
  "components": "${cwd}/src/components",
  "plugins": "${cwd}/src/plugins",
  "store": "${cwd}/src/store",
  "utils": "${cwd}/src/utils",
  "views": "${cwd}/src/views",
  "rootAssets": "${cwd}/../../Plugins/src/assets",
  "rootPlugins": "${cwd}/../../Plugins/src/plugins",
  "rootUtils": "${cwd}/../../Plugins/src/utils"
},
```

那些 `root` 开头的路径是不一样的

**Comment by IWANABETHATGUY** [comment]
我这边是正常的。

**Comment by HenryTSZ** [comment]
@IWANABETHATGUY 我想问一下 `.pathaliasrc` 和 在项目根目录的 `.vscode/setting.json` 和 全局的 `setting.json` 这三个配置的优先级. 

处理的时候会将这几个的配置合并吗? 比如 `.pathaliasrc` 有一些路径配置, `setting.json` 有一些路径配置, 都不冲突, 是会合并还是只取优先级最高的配置?

现在有从 `vue.config.json`, `webpack.config.json` 中获取 `alias` 吗?

**Comment by IWANABETHATGUY** [comment]
pathaliasrc > package.json > settings.json, 暂时不准备从vue.config.json, webpack.config.json 里取。

**Comment by HenryTSZ** [comment]
终于找到为啥不生效了, `.pathaliasrc` 只在刚使用 `vscode` 打开项目时生效, 以后再修改里面的路径别名后不会实时更新路径别名, 必须再重新使用 `vscode` 打开才能生效
