### ISSUE TITLE
支持模块导入路径重构吗？

### ISSUE THREAD

**Issue by fyyhome** [IWANABETHATGUY/vscode-path-alias#39]
目前该工具支持**相对路径**转**绝对路径**的重构吗？readme上写的支持，可是没看到使用说明。。。

**Comment by IWANABETHATGUY** [comment]
![path-alias-refactor](https://user-images.githubusercontent.com/17974631/90488739-ebfb7980-e16e-11ea-8e03-0ea9d6d59f6c.gif)

**Comment by fyyhome** [comment]
感谢解答，貌似还不太行，配置都打开了，但是没有自动提示。

**Comment by IWANABETHATGUY** [comment]
> 置都打开了，但是没有自动提示。
所有的功能都用不了吗？

**Comment by IWANABETHATGUY** [comment]
点击小灯泡，第8行

**Comment by IWANABETHATGUY** [comment]
```json
"pathAlias.aliasMap": {
    "@": "${cwd}",
    "~assets": "${cwd}/src/assets"
  },
```
尝试加一下这个到你的 vscode 设置里面 `setting.json`

**Comment by unomisa** [comment]
![image](https://user-images.githubusercontent.com/61730415/117793956-56b18f80-b27f-11eb-96ab-7d2be506f7db.png)
将最后一个设置关掉，成功！！😂
