### ISSUE TITLE
插件内存占用过大，其他非常完美

### ISSUE THREAD

**Issue by wanguano** [IWANABETHATGUY/vscode-path-alias#40]
问题：内存占用过大，当我开启插件时，占用内存资源最低200MB作用，其他的非常棒👍

**Comment by zyzweb** [comment]
想问一下,怎么判断插件内存占用过大

**Comment by zyzweb** [comment]
@wanguano 想问一下,怎么判断插件内存占用过大

**Comment by wanguano** [comment]
> @wanguano想问一下，怎么判断插件内存占用过大

现在好多了，作者应该优化过了
判断插件占用的话：任务管理器，启用插件占比和禁用插件查看，你对比下就好了

**Comment by IWANABETHATGUY** [comment]
已优化
