### ISSUE TITLE
开启此插件占用cpu200%-500%

### ISSUE THREAD

**Issue by bluexuchun** [IWANABETHATGUY/vscode-path-alias#42]
Mac 开启此插件后占用cpu率非常大，这个问题该怎么解决？
一旦开启此插件 电脑风扇疯狂转动 耗电快 CPU占率高

**Comment by IWANABETHATGUY** [comment]
Duplicate of #33

**Comment by IWANABETHATGUY** [comment]
你可以看下 #33 这个issue 需要你把 这个文件上传一下， 我好看是什么原因导致的
