### ISSUE TITLE
能够支持.vue文件中css跳转吗

### ISSUE THREAD

**Issue by zyzweb** [IWANABETHATGUY/vscode-path-alias#43]

**Comment by IWANABETHATGUY** [comment]
你说的是这种吗？
![image](https://user-images.githubusercontent.com/17974631/106479220-076ffc00-64e5-11eb-8d0e-e227470e9b93.png)
如果是的话，目前就是支持的。
如果不是的话，还需要你能举个例子

**Comment by IWANABETHATGUY** [comment]
你说的是这种路径跳转吗？
![image](https://user-images.githubusercontent.com/17974631/106479338-325a5000-64e5-11eb-9b76-1edb0ff0a391.png)
这种目前是支持的， 如果不是的话最好能给下demo

**Comment by zyzweb** [comment]
![image](https://user-images.githubusercontent.com/41266834/106689931-ccb4b380-660b-11eb-982b-74c3f0722b50.png)
![image](https://user-images.githubusercontent.com/41266834/106689951-d76f4880-660b-11eb-96a3-baff26ae7299.png)
同一个vue文件,template的class跳转到style中的class,这个可以支持吗?

**Comment by IWANABETHATGUY** [comment]
这个可以给 `vetur` 提个issue， 这个 feature 不用 parser 来做分析应该是做不到很准确, 加了会让vscode 响应的更慢
