### ISSUE TITLE
能直接读取配置文件比如vue.config.js中的alias?                                                                                                                                                                                                                                                            

### ISSUE THREAD

**Issue by zyzweb** [IWANABETHATGUY/vscode-path-alias#44]
![image](https://user-images.githubusercontent.com/41266834/101243902-2ef15500-373e-11eb-831d-b1d16b52d8d3.png)
![image](https://user-images.githubusercontent.com/41266834/101243945-70820000-373e-11eb-8d46-a40d6720db28.png)
能实现不用手动配置,自动读取配置文件吗,react也同理

**Comment by IWANABETHATGUY** [comment]
添加配置文件可以通过package.json 字段pathalias 或者在根目录下的.pathaliasrc(以json格式书写)配置路径别名

**Comment by IWANABETHATGUY** [comment]
目前有几种方式， 你可以不单独新建一份 `.pathaliasrc` 配置文件，读取的话，因为不同的框架有不同的 配置文件， 这个很难达到用户想要的效果。
