### ISSUE TITLE
引入的时候省略 '/index' 无法跳转

### ISSUE THREAD

**Issue by HenryTSZ** [IWANABETHATGUY/vscode-path-alias#46]
目录结构为:

```
├─api
│ ├─index.js
```

`.pathaliasrc` 配置为:

```json
{
  "@": "${cwd}/src",
  "api": "${cwd}/src/api"
}
```

跳转录屏:

![1](https://user-images.githubusercontent.com/55341525/106544120-fc978480-6541-11eb-9fe8-b2598df7041a.gif)

**Comment by IWANABETHATGUY** [comment]
你这个应该不是 `path-alias` 提供的跳转， 我估计你把 `path-alias` 禁用 可能对这个效果没有什么影响。

**Comment by HenryTSZ** [comment]
禁用以后都不可以跳转了

![11](https://user-images.githubusercontent.com/55341525/106545923-3cac3680-6545-11eb-972f-fcf1e6c593ad.gif)
