### ISSUE TITLE
能够支持相对路径跳转吗?

### ISSUE THREAD

**Issue by zyzweb** [IWANABETHATGUY/vscode-path-alias#47]
![image](https://user-images.githubusercontent.com/41266834/106689632-4304e600-660b-11eb-8092-321d77e71845.png)
上面的alias模式可以跳转,下面的也可以通过小灯泡重构路径,可否直接通过相对路径跳转呢?

**Comment by zyzweb** [comment]
有些时候用相对路径比较方便,特别是在层级接近的情况下

**Comment by IWANABETHATGUY** [comment]
我看了下vetur 是支持相对路径跳转的，如果有任何问题可以重新开一个issue
