### ISSUE TITLE
相对路径重构后路径分隔符问题

### ISSUE THREAD

**Issue by unomisa** [IWANABETHATGUY/vscode-path-alias#49]
![lujing](https://user-images.githubusercontent.com/61730415/117798079-4dc2bd00-b283-11eb-9fee-35d04fc804eb.gif)

1. 相对路径转换后，路径分隔符为`\`，正确应该为`/`，需手动转换
2. 在`vue cli4 `中 `webpack `默认对 `@` 定位至`src`目录，因此每次重构后还需要手动删除`/src`的路径才能正确定位

### 因此是否能手动配置重构后的路径格式？

**Comment by IWANABETHATGUY** [comment]
这的确个问题，我最近没时间修复，应该过段时间会修复

**Comment by unomisa** [comment]
对了老哥，没有其它能联系你的方式，所以只能在这里说个题外话。

#### 你还有你当时写`README`的主题配置方案吗，那个主题颜色我好爱🙈

**Comment by unomisa** [comment]
> https://github.com/yutent/one-plain, 字体 dank mono，付费字体。可以用 "editor.fontFamily": "JetBrains mono", 代替

太谢谢啦😆

**Comment by IWANABETHATGUY** [comment]
第二个问题，在你项目的package.json 中添加 
```
"pathalias": {
    "@": "${cwd}/src"
  }
```
即可

**Comment by IWANABETHATGUY** [comment]
升级到最新0.12.1
